const itemData = [
    {
        name: "Aaliyah Graphic Tee",
        brand: "Lewis Cupper",
        price: "34.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "aaliyah_t.jpeg",
    },
    {
        name: "Wu-Tang Graphic Tee",
        brand: "DA WU",
        price: "44.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "wutangshirts.png",
    },
    {
        name: "Battleground Tour Tee",
        brand: "BG Merch",
        price: "49.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "battleground_t.jpeg",
    },
    {
        name: "Budweiser Plain Text Thermal",
        brand: "Frisco X Budweiser",
        price: "79.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "budweiser_thermal.jpeg",
    },
    {
        name: "Black Cargo Pants",
        brand: "8 Down",
        price: "119.99",
        category: "clothing",
        subcategory: "pants",
        imgPath: "cargo_pants_black.jpeg",
    },
    {
        name: "Columbia Scholar Tee",
        brand: "Graduate",
        price: "39.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "columbia_t.jpeg",
    },
    {
        name: "Fenty Graffiti Tee",
        brand: "Super Bowl X Fenty",
        price: "59.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "fenty_t.jpeg",
    },
    {
        name: "Black Flared Trousers",
        brand: "MWARNA",
        price: "139.99",
        category: "clothing",
        subcategory: "pants",
        imgPath: "flare_trousers_black.jpeg",
    },
    {
        name: "Fleece Sweats",
        brand: "Lewis Cupper",
        price: "59.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "fleece_sweats.jpeg",
    },
    {
        name: "Harvard Scholar Tee",
        brand: "Graduate",
        price: "39.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "harvard_t.jpeg",
    },
    {
        name: "Light Washed Bootcut Jeans",
        brand: "Klevi's",
        price: "59.99",
        category: "clothing",
        subcategory: "pants",
        imgPath: "lightwash_bootcut.jpeg",
    },
    {
        name: "Outkast Tour Tee",
        brand: "BG Merch",
        price: "49.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "outkast_t.jpeg",
    },
    {
        name: "Vintage Pinks Graphic Tee",
        brand: "Pinks",
        price: "74.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "pinks_t.jpeg",
    },
    {
        name: "Self Care Tee",
        brand: "Flower Pot",
        price: "39.99",
        category: "clothing",
        subcategory: "shirts",
        imgPath: "self_care_t.jpeg",
    },
    {
        name: "Olive Cargo Trousers",
        brand: "8 Down",
        price: "69.99",
        category: "clothing",
        subcategory: "pants",
        imgPath: "slim_cargo_olive.jpeg",
    },
    {
        name: "1998 NBA Finals Hat",
        brand: "Old Era",
        price: "19.99",
        category: "accessories",
        subcategory: "hats",
        imgPath: "1998_finals.jpeg",
    },
    {
        name: "Fadidas Hoodie",
        brand: "Fadidas",
        price: "64.99",
        category: "clothing",
        subcategory: "hoodies",
        imgPath: "adidas_hoodie.jpeg",
    },
    {
        name: "Vintage Hoodie",
        brand: "Rodd Cambridge",
        price: "74.99",
        category: "clothing",
        subcategory: "hoodies",
        imgPath: "balance_hoodie.jpeg",
    },
    {
        name: "Beetlejuice Hoodie",
        brand: "Beetlejuice X MISS ME YET?",
        price: "89.99",
        category: "clothing",
        subcategory: "hoodies",
        imgPath: "beetlejuice_hoodie.jpeg",
    },
    {
        name: "Black Square Sunglasses",
        brand: "FRISCO",
        price: "179.99",
        category: "accessories",
        subcategory: "sunglasses",
        imgPath: "black_square_glasses.jpeg",
    },
    {
        name: "Air Poormon BRED 1",
        brand: "ZIKE",
        price: "2.00",
        category: "shoes",
        subcategory: "sneakers",
        imgPath: "bred_1.jpeg",
    },
    {
        name: "Checkered Slide-on Vans",
        brand: "Vans",
        price: "39.99",
        category: "shoes",
        subcategory: "casual",
        imgPath: "checkered_vans.jpeg",
    },
    {
        name: "Cherry 8-hole Boot",
        brand: "Dr. Martens",
        price: "119.99",
        category: "shoes",
        subcategory: "boots",
        imgPath: "cherry_dr_martens.jpeg",
    },
    {
        name: "Beige Wallabee Shoes",
        brand: "Clarks",
        price: "159.99",
        category: "shoes",
        subcategory: "casual",
        imgPath: "clarks.jpeg",
    },
    {
        name: "Classic All-Stars",
        brand: "Converse",
        price: "29.99",
        category: "shoes",
        subcategory: "casual",
        imgPath: "classic_converse.jpeg",
    },
    {
        name: "Clubmaster Sunglasses",
        brand: "Ray Got Banned",
        price: "169.99",
        category: "accessories",
        subcategory: "sunglasses",
        imgPath: "clubmaster_glasses.jpeg",
    },
    {
        name: "Marble Beanie",
        brand: "Columbia",
        price: "19.99",
        category: "accessories",
        subcategory: "hats",
        imgPath: "columbia_beanie.jpeg",
    },
    {
        name: "Cuban Link Ring",
        brand: "FRISCO",
        price: "79.99",
        category: "accessories",
        subcategory: "jewelry",
        imgPath: "cuban_ring.jpeg",
    },
    {
        name: "Black 8-hole Boot",
        brand: "Dr Martens",
        price: "139.99",
        category: "shoes",
        subcategory: "boots",
        imgPath: "dr_martens.jpeg",
    },
    {
        name: "Save The Earth Slide-On Vans",
        brand: "Vans",
        price: "59.99",
        category: "shoes",
        subcategory: "casual",
        imgPath: "earth_vans.jpeg",
    },
    {
        name: "Green Beanie",
        brand: "Bayern Tumeric",
        price: "19.99",
        category: "accessories",
        subcategory: "hats",
        imgPath: "green_beanie.jpeg",
    },
    {
        name: "Green Square Sunglasses",
        brand: "FRISCO",
        price: "179.99",
        category: "accessories",
        subcategory: "sunglasses",
        imgPath: "green_square_glasses.jpeg",
    },
    {
        name: "Jordan 4",
        brand: "Trike",
        price: "199.99",
        category: "shoes",
        subcategory: "sneakers",
        imgPath: "jordan_4.jpeg",
    },
    {
        name: "Metal Square Sunglasses",
        brand: "FRISCO",
        price: "124.99",
        category: "accessories",
        subcategory: "sunglasses",
        imgPath: "metal_square_glasses.jpeg",
    },
    {
        name: "Obsessed Zip-Up Hoodie",
        brand: "Number5",
        price: "89.99",
        category: "clothing",
        subcategory: "hoodies",
        imgPath: "obsessed_hoodie.jpeg",
    },
    {
        name: "Pearl Smiley Bracelet",
        brand: "FRISCO",
        price: "49.99",
        category: "accesories",
        subcategory: "jewelry",
        imgPath: "pearl_bracelet.jpeg",
    },
    {
        name: "Pearl Necklace",
        brand: "FRISCO",
        price: "69.99",
        category: "accessories",
        subcategory: "jewelry",
        imgPath: "pearl_necklace.jpeg",
    },
    {
        name: "Rainbow Baguette Ring",
        brand: "FRISCO",
        price: "699.99",
        category: "accessories",
        subcategory: "jewelry",
        imgPath: "rainbow_ring.jpeg",
    },
    {
        name: "Sneaks For Freaks",
        brand: "Reebok",
        price: "30.00",
        category: "shoes",
        subcategory: "sneakers",
        imgPath: "reebok.jpeg",
    },
    {
        name: "Rolling Stones Hat",
        brand: "UNKNOWN",
        price: "29.99",
        category: "accessories",
        subcategory: "hats",
        imgPath: "rolling_stones_hat.jpeg",
    },
    {
        name: "Subtle Message Hoodie",
        brand: "Lifeline",
        price: "39.99",
        category: "clothing",
        subcategory: "hoodies",
        imgPath: "stay_strong_hoodie.jpeg",
    },
    {
        name: "Tinted Studio Glasses",
        brand: "FRISCO",
        price: "299.99",
        category: "accessories",
        subcategory: "sunglasses",
        imgPath: "studio_glasses.jpeg",
    },
    {
        name: "Studio Hoodie",
        brand: "Day28",
        price: "99.99",
        category: "clothing",
        subcategory: "hoodies",
        imgPath: "studio_hoodie.jpeg",
    },
    {
        name: "Suede Vans",
        brand: "Vans",
        price: "49.99",
        category: "shoes",
        subcategory: "casual",
        imgPath: "suede_vans.jpeg",
    },
    {
        name: "Tennis Chain Necklace",
        brand: "FRISCO",
        price: "499.99",
        category: "accessories",
        subcategory: "jewelry",
        imgPath: "tennis_necklace.jpeg",
    },
    {
        name: "Textured All-Star",
        brand: "Converse",
        price: "49.99",
        category: "shoes",
        subcategory: "casual",
        imgPath: "textured_converse.jpeg",
    },
    {
        name: "Timberland Boots",
        brand: "Timberland",
        price: "199.99",
        category: "shoes",
        subcategory: "boots",
        imgPath: "timberland.jpeg",
    },
    {
        name: "Green Timberland Boots",
        brand: "Timberland",
        price: "199.99",
        category: "shoes",
        subcategory: "boots",
        imgPath: "green_timberland.jpeg",
    },
    {
        name: "Prem Air Max 1",
        brand: "Travis Scott X Likey",
        price: "259.99",
        category: "shoes",
        subcategory: "sneakers",
        imgPath: "travis_airmax_1.jpeg",
    },
    {
        name: "Yankees Fitted Cap",
        brand: "Tru Era",
        price: "29.99",
        category: "accessories",
        subcategory: "hats",
        imgPath: "yankees_fitted.jpeg",
    },
];
